# Security
lch_login:
    path: /admin/login
    defaults: { _controller: 'Lch\UserBundle\Controller\Security\SecurityController::login' }
lch_logout:
    path: /admin/logout

# Resetting
lch_request_password:
    path: /resetting/request-password
    defaults: { _controller: 'Lch\UserBundle\Controller\Security\ResettingController::requestPassword' }

lch_send_email:
    path: /resetting/send-email
    defaults: { _controller: 'Lch\UserBundle\Controller\Security\ResettingController::sendEmail' }

lch_check_email:
    path: /resetting/check-email
    defaults: { _controller: 'Lch\UserBundle\Controller\Security\ResettingController::checkEmail' }

lch_reset_email:
    path: /resetting/reset/{token}
    defaults: { _controller: 'Lch\UserBundle\Controller\Security\ResettingController::reset' }

# Registration
lch_registration:
    path: /registration
    defaults: { _controller: 'Lch\UserBundle\Controller\Security\RegistrationController::register'}