parameters:
  lch_user.create_command.class: Lch\UserBundle\Command\CreateUserCommand

services:
  lch_user.mailer:
    class: '%lch_user.classes.mailer%'
    arguments: ['@router', '@twig', '@swiftmailer.mailer.default']

  lch_user.token_generator:
    class: '%lch_user.classes.token_generator%'

  lch_user.password_manager:
    class: '%lch_user.classes.password_manager%'
    arguments: ['@security.encoder_factory', '@security.user_password_encoder.generic']

  lch_user.user_manager:
    class: '%lch_user.classes.user_manager%'
    arguments: ['@doctrine.orm.entity_manager', '@lch_user.password_manager', '%lch_user.classes_array%']

  lch_user.command.create:
    class: '%lch_user.create_command.class%'
    arguments: ['@lch_user.user_manager']
    tags:
      - { name: console.command }

  lch_user.type.registration:
    class: '%lch_user.forms.registration%'
    tags:
        - { name: form.type }
